name       : libdiscid
version    : 0.6.2
release    : 3
source     :
    - https://github.com/metabrainz/libdiscid/archive/v0.6.2.tar.gz : a9b73b030603ce707941a3aab4f46649fa5029025e7e2bfbbe0c3c93a86d7b20
homepage   : http://musicbrainz.org/doc/libdiscid
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : C library for creating MusicBrainz DiscIDs from audio CDs.
description: |
    libdiscid is a C library for creating MusicBrainz DiscIDs from audio CDs. It reads a CD's table of contents (TOC) and generates an identifier which can be used to lookup the CD at MusicBrainz (http://musicbrainz.org). Additionally, it provides a submission URL for adding the DiscID to the database.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
