name       : libdiscid
version    : 0.6.1
release    : 1
source     :
    - http://ftp.musicbrainz.org/pub/musicbrainz/libdiscid/libdiscid-0.6.1.tar.gz : aceb2bd1a8d15d69b2962dec7c51983af32ece318cbbeb1c43c39802922f6dd5
license    : GPL-2.0
component  : multimedia.library
summary    : C library for creating MusicBrainz DiscIDs from audio CDs.
description: |
    libdiscid is a C library for creating MusicBrainz DiscIDs from audio CDs. It reads a CD's table of contents (TOC) and generates an identifier which can be used to lookup the CD at MusicBrainz (http://musicbrainz.org). Additionally, it provides a submission URL for adding the DiscID to the database.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
