name       : libdiscid
version    : 0.6.4
release    : 4
source     :
    - https://github.com/metabrainz/libdiscid/archive/v0.6.4.tar.gz : c581baeabaf6e410398005645d66acaaa41ff2cab272c267a2d6839e41486ebb
homepage   : http://musicbrainz.org/doc/libdiscid
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : C library for creating MusicBrainz DiscIDs from audio CDs.
description: |
    libdiscid is a C library for creating MusicBrainz DiscIDs from audio CDs. It reads a CD's table of contents (TOC) and generates an identifier which can be used to lookup the CD at MusicBrainz (http://musicbrainz.org). Additionally, it provides a submission URL for adding the DiscID to the database.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
